<?php
/**
 * Created by PhpStorm.
 * User: litian
 * Date: 2017/4/24
 * Time: 17:09
 */
namespace including\model;

use core\lib\mysql\modelMedoo;

class Model extends modelMedoo
{
    public function __construct()
    {
        parent::__construct();
    }

    public function select($where = null, $field = null)
    {
        return parent::select($where, $field); // TODO: Change the autogenerated stub
    }

    public function find($where, $field)
    {
        if(!$field || empty($field)){
            $field = '*';
        }
        if(is_array($field)){
            $field = implode(',', $field);
        }

        $data = $this->select($where, $field);
        return isset($data[0]) ? $data[0] : array();
    }
}